### ISSUE TITLE
Test everything missing tests

### ISSUE THREAD

**Issue by ajs1998** [ajs1998/Dag#2]
- [x] There should be 100% test coverage
- [x] Tests should be passing for Java 8 and up

**Comment by ajs1998** [comment]
`HashDag` is only missing test coverage for both `toArray()` methods and the `iterator()` method.
`DagIterator` remains mostly untested

**Comment by 9baller47** [comment]
> * [ ]  There should be 100% test coverage
> * [ ]  Tests should be passing for Java 8 and up

Hi there
